
### Passengers
POST http://localhost:5000/api/passengers/create HTTP/1.1
content-type: application/json

{
    "fullName": "Daniel Zemlyanov Ilich",
    "passport": "5555 342345",
    "seatNumber": "23b"
}

###
GET http://localhost:5000/api/passengers/ HTTP/1.1
content-type: application/json


###
PUT http://localhost:5000/api/passengers/change HTTP/1.1
content-type: application/json

{
    "fullName": "Daniel Zemlyanov DADA",
    "passport": "5555 342345",
    "seatNumber": "23s"
}

###
DELETE http://localhost:5000/api/passengers/remove HTTP/1.1
content-type: application/json

{
    "passport": "5555 342345"
}






### Flights
POST http://localhost:5000/api/flights/create HTTP/1.1
content-type: application/json

{
    "departureAirportId": 1696858154030,
    "destinationAirportId": 1696858216580,
    "flightPrice": 5500,
    "flightDuration": 500
}


### 
GET http://localhost:5000/api/flights/ HTTP/1.1
content-type: application/json


### 
PUT http://localhost:5000/api/flights/change HTTP/1.1
content-type: application/json

{
    "flightNumber": "112234434",
    "departureAirportId": "1",
    "destinationAirportId": "2",
    "flightDuration": 700,
    "flightPrice": 5500,
    "flightStatus": "active"
}

###
DELETE http://localhost:5000/api/flights/remove HTTP/1.1
content-type: application/json

{
    "flightNumber": "ABK4607"
}

###
GET http://localhost:5000/api/passengers/ HTTP/1.1
content-type: application/json







### Airports
POST http://localhost:5000/api/airports/create HTTP/1.1
content-type: application/json

{
    "airportName": "Кольцово",
    "airportPlace": "Екатеринбург"
}

###
GET http://localhost:5000/api/airports/ HTTP/1.1
content-type: application/json

### 
PUT http://localhost:5000/api/airports/change HTTP/1.1
content-type: application/json

{
    "airportId": 1696857507411,
    "airportPlace": "Москва"
}


### Planes
GET http://localhost:5000/api/planes/ HTTP/1.1
content-type: application/json

###
POST http://localhost:5000/api/planes/create HTTP/1.1
content-type: application/json

{
    "planeType": "BN800",
    "seatCount": 80
}

###
PUT http://localhost:5000/api/planes/change HTTP/1.1
content-type: application/json

{
    "id": 1696948058683,
    "seatCount": 60
}

###
DELETE http://localhost:5000/api/planes/remove HTTP/1.1
content-type: application/json

{
    "id": 1696948055200
}



### Admin
GET http://localhost:5000/api/admins/ HTTP/1.1
content-type: application/json

### 
POST http://localhost:5000/api/admins/create HTTP/1.1
content-type: application/json

{
    "fullName": "Александра Солдатова",
    "password": "danilushka",
    "secretWord": "badumtss"
}

### 
POST http://localhost:5000/api/admins/login HTTP/1.1
content-type: application/json

{
    "fullName": "Землянов Даниил Ильич",
    "password": "password1",
    "secretWord": "kotik"
}

###
PUT http://localhost:5000/api/admins/change HTTP/1.1
content-type: application/json

{
    "fullName": "Саша Солдатова",
    "password": "qwertwerwe",
    "secretWord": "badumtss"
}

###
DELETE http://localhost:5000/api/admins/remove HTTP/1.1
content-type: application/json

{
    "id": "6526786cda771e8524f56d4f" 
}